robot_dreams_de:
  api:
    base_url: "https://robot-dreams-de-api.herokuapp.com"
    endpoints:
      authentication: "/auth"
      out_of_stock: "/out_of_stock"
    credentials:
      username: "topsecret"
      password: "topsecret"
  storage:
    path: "./data/"
