robot_dreams_de:
  api:
    base_url: "https://robot-dreams-de-api_client.herokuapp.com"
    endpoints:
      authentication: "/auth"
      out_of_stock: "/out_of_stock"
    credentials:
      username: "secret"
      password: "secret"
  storage:
    path: "/home/user/api_dump/"
