robot_dreams_de:
  api:
    timeout: 60
    base_url: "https://robot-dreams-de-api.herokuapp.com"
    endpoints:
      authentication: "/auth"
      out_of_stock: "/out_of_stock"
  storage:
    path: "/bronze/api_dump/"
